essay/urls.py
from django.urls import path

from . import views

# essay模块的路由

app_name = 'essay'  # 一定要指定命名空间

urlpatterns = [
    path('', views.index, name='index'),
    path('essayajax', views.essayajax, name='essayajax'),
    path('essaysearch',views.essaySearch, name='essaysearch'),
    path('getessay',views.getEssay, name='getessay'),
    path('timetree',views.timeTree, name='timetree')
]

sunshinelife/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('user/', include("user.urls")),  # 导入user模块的路由

    path('', include("essay.urls"))   # 导入essay模块的路由

    # 登录路由查询字符的方式
    # path('user', user_view.login),
    # 登录路由在path中携带
    # 限制类型  int  str  slug uuid path
    # path('user/<int:user_id>/<user_name>', user_view.login_path)
]

user/urls.py
from django.urls import path

from . import views

# user模块的路由

app_name = 'user'  # 一定要指定命名空间

urlpatterns = [
    #用户
    path('index', views.index, name='user_index'),
    path('login', views.user_login, name='user_login'),
    path('register', views.register, name='user_register'),
    path('userupdate', views.userUpdate, name='user_update'),

    #类型
    path('gettype', views.getType, name='user_gettype'),
    path('addtype', views.addType, name='user_addtype'),
    path('alltype', views.allType, name='user_alltype'),
    path('updatetype', views.updateType, name='user_updatetype'),
    path('updatetypestu', views.updateTypeStu, name='user_updatetypestu'),


    #文章

    path('getessay', views.getEssay, name='user_getessay'),
    path('addessay', views.addEssay, name='user_addessay'),
    path('allessay', views.allEssay, name='user_allessay'),
    path('updateessay', views.updateEssay, name='user_updateessay'),
    path('updateessaystu', views.updateEssayStu, name='user_updateessaystu'),

    #公告
    path('getside', views.getSide, name='user_getside'),
    path('addside', views.addSide, name='user_addside'),
    path('allside', views.allSide, name='user_allside'),

    # 类型
    path('gettree', views.getTree, name='user_gettree'),
    path('addtree', views.addTree, name='user_addtree'),
    path('alltree', views.allTree, name='user_alltree'),
    path('updatetree', views.updateTree, name='user_updatetree'),
    path('updatetreestu', views.updateTreeStu, name='user_updatetreestu'),

    # path('url', views.url, name='user_login'),
    # path('add', views.user_add, name='user_add'),
    # path('query',views.user_query,name='user_query'),
    # path('update', views.user_update, name='user_update'),
    # path('delete', views.user_delete, name='user_del')
]

essay/models.py
from django.db import models
import datetime


# Create your models here.
class essay_type(models.Model):  # 类型
    typeid = models.AutoField(primary_key=True)  # 类型id
    type = models.CharField(max_length=10, null=True)  # 类型名称
    created = models.DateTimeField(auto_now_add=True)  # 创建时间
    updatetime = models.DateTimeField(auto_now=True)  # 修改时间
    remark = models.CharField(max_length=60, null=True, blank=True)  # 备注
    status = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        db_table = 'essay_type'


class essay(models.Model):
    essayid = models.AutoField(primary_key=True)  # 文章id
    title = models.CharField(max_length=60, null=True)  # 文章标题
    content = models.TextField(null=True)  # 内容
    created = models.DateTimeField(auto_now_add=True)  # 创建时间
    updatetime = models.DateTimeField(auto_now=True)  # 修改时间
    remark = models.CharField(max_length=60, null=True, blank=True)  # 备注
    status = models.CharField(max_length=20, null=True, blank=True)
    typedata = models.ForeignKey("essay_type", on_delete=models.CASCADE)

    class Meta:
        db_table = 'essay'


class side(models.Model):
    message = models.TextField(null=True)

    class Meta:
        db_table = 'side'


class timeTree(models.Model):
    event = models.TextField(null=True)  # 事件
    created = models.DateTimeField(auto_now_add=True)  # 创建时间
    updatetime = models.DateTimeField(auto_now=True)  # 修改时间
    status = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        db_table = 'timetree'

essay/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods

from django.forms import model_to_dict
# Create your views here.
from .models import *
from .models import timeTree as  tt
from tool.Tool import *


# 初始方法
def index(request):
    if request.method == 'GET':  # 判断是否分类选择
        typeid = request.GET.get('typeid', None)
        request.session["typeid"] = typeid  # 向session中存储查typeid
        request.session["keywords"] = None  # 将关键词查询设为none
    # 文章类型检索
    all_type = essay_type.objects.filter(status=1)
    typedb = []
    for item in all_type:
        typedb.append({
            'typeid': item.typeid,
            'type': item.type,
        })
    # 公告检索
    sidedb = side.objects.order_by('-id')
    # 近期文章检索
    essaydb = essay.objects.filter(status=1).order_by('-created')[:6]
    recent = []
    for item in essaydb:
        recent.append({'title': item.title, 'essayid': item.essayid})

    context = {'typedb': typedb, 'message': sidedb[0].message, "recent": recent, 'essaydata': None}
    return render(request, 'index.html', context=context)


# 关键词查询文章
@require_http_methods(['GET', 'POST'])
def essaySearch(request):
    if request.method == 'GET':
        keywords = request.GET.get('keywords', None)  # 获取关键词
        request.session["keywords"] = keywords  # 存储关键词
        request.session["typeid"] = None  # 将类型查询的设为none

        # 文章类型检索
        all_type = essay_type.objects.filter(status=1)
        typedb = []
        for item in all_type:
            typedb.append({
                'typeid': item.typeid,
                'type': item.type,
            })
        # 公告检索
        sidedb = side.objects.order_by('-id')
        # 近期文章检索
        essaydb = essay.objects.filter(status=1).order_by('-created')[:6]
        recent = []
        for item in essaydb:
            recent.append({'title': item.title, 'essayid': item.essayid})

        context = {'typedb': typedb, 'message': sidedb[0].message, "recent": recent, 'essaydata': None}
        return render(request, 'index.html', context=context)


# 文章内容ajax处理
@require_http_methods(['GET', 'POST'])
def essayajax(request):
    typeid = request.session["typeid"]
    keywords = request.session["keywords"]
    if typeid is not None and keywords is None:  # 分类查询时
        essaydb = essay.objects.filter(status=1, typedata=typeid).order_by('-created')
    elif typeid is None and keywords is not None:  # 关键字查询时
        essaydb = essay.objects.filter(status=1, title__contains=keywords).order_by('-created')
    else:  # 默认查询
        essaydb = essay.objects.filter(status=1).order_by('-created')

    page = request.GET.get('page', 1)  # 获取页数
    paginator_data = Paginator(essaydb, 6).get_page(page)  # 设置获取的页数与数量 6
    total_pages = Paginator(essaydb, 6).num_pages  # 获取总页
    essaydata = []
    for item in paginator_data:
        date = getdate(item.created)
        content = remove_html_tags(item.content)
        essaydata.append({
            'createtime': date,
            'title': item.title,
            'essayid': item.essayid,
            'typedata': item.typedata.type,
            'content': content
        })
        # keywords = request.session["keywords"]
    context = result(1, 200, total_pages, essaydata)
    return JsonResponse(context, safe=False)


# 关键词查询文章
@require_http_methods(['GET', 'POST'])
def getEssay(request):
    if request.method == 'GET':
        essayid = request.GET.get('essayid')
        essaydb = essay.objects.get(essayid=essayid)
        date = getdate(essaydb.created)
        essaydata = []
        essaydata.append({
            'createtime': date,
            'title': essaydb.title,
            'essayid': essaydb.essayid,
            'typedata': essaydb.typedata.type,
            'content': essaydb.content
        })
        context = result(1, 200, 0, essaydata)
        return JsonResponse(context, safe=False)


#  时间树
@require_http_methods(['GET', 'POST'])
def timeTree(request):
    if request.method == 'GET':
        data = tt.objects.filter(status=1).order_by('-created')
        timeTreedata = []
        for item in data:
            date = getdate(item.created)
            timeTreedata.append({
                'createtime': date,
                'event': item.event,
            })
        context = result(1, 200, 0, timeTreedata)
        return JsonResponse(context, safe=False)

essay/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SunShine-Life</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'layui/layui.js' %}"></script>
    {#    calendar#}
    <link rel="icon" href="{% static 'img/sunshine.svg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'img/sunshine.svg' %}" type="image/x-icon">
</head>

<body>
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo layui-hide-xs layui-bg-black">layout demo</div>
        <ul class="layui-nav layui-bg-gray"
            style="text-align: center; background-image: linear-gradient(to top, #cfd9df 0%, #e2ebf0 100%)!important; padding: 0 0 ">
            <li class="layui-nav-item" style="float: left;"><img src="{% static 'img/logo-CN.png' %}"
                                                                 width="200" height="50"></li>
            <li class="layui-nav-item"><a class="alink" href="{% url 'essay:index' %}">首页</a></li>
            <li class="layui-nav-item">
                <a href="javascript:;">分类</a>
                <dl class="layui-nav-child">
                    {% for item in typedb %}
                        <dd><a href="{% url 'essay:index' %}?typeid={{ item.typeid }}">{{ item.type }}</a></dd>
                    {% endfor %}
                </dl>
            </li>
            <li class="layui-nav-item"><a id="timetree" style="cursor: pointer;">时间树</a></li>

            <li class="layui-nav-item">
                <div class="layui-form">
                    <div class="layui-input-wrap">
                        <input type="text" lay-affix="search" lay-filter="search"
                               lay-options="{split: true}" placeholder="搜索文章"
                               class="layui-input">
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="layui-side layui-bg-black"
         style="background-image: linear-gradient(45deg, #93a5cf 0%, #e4efe9 100%)!important; text-align: center;height: 888px; overflow: hidden;color: #1f1f1f !important">
        <br>
        <img src="{% static 'img/sunshine.svg' %}" class="layui-nav-img" style="width: 150px;height:150px">
        <br>
        <br>
        <div class="layui-panel"
             style="background-image: linear-gradient(45deg, #93a5cf 0%, #e4efe9 100%)!important; text-align: center;height: 200px">
            {{ message|safe }}
        </div>
        <br>
        <div class="parent" style="height: 440px">
            <div><h2 style="float: left">近期</h2></div>
            <br>
            <div class="layui-text" style="padding-left:25px;">
                <ul>
                    {% for item in recent %}
                        <li style="list-style-type:upper-roman;">
                            <p class="read" id="essayClickParent{{ forloop.counter }}"
                               essayid="{{ item.essayid }}">{{ item.title }}</p>
                        </li>

                    {% endfor %}
                </ul>
            </div>
            <span style="color: #1f1f1f !important" class="child-at-bottom">
                <a href="{% url 'user:user_login' %}" style="color: rgba(26,26,26,0.93) !important">登录</a> &nbsp;&nbsp;&nbsp;&nbsp;
                <a style="color: rgba(26,26,26,0.93) !important"> MORE</a>
            </span>
        </div>
    </div>
    <div class="layui-body parent" id="body" style="background-color:#ece0bc!important; height: auto">
        <div class="flow-demo" id="ID-flow-demo" style="background-color:#ece0bc!important; height: auto">
            <div class="layui-row layui-col-space15">
            </div>
        </div>
    </div>
    <div class="layui-footer"
         style="color: black;background-image: linear-gradient(to top, #accbee 20%, #e7f0fd 100%) !important; text-align: center">
        底部固定区域
    </div>
</div>

<script>
    layui.use(function () {
        var $ = layui.jquery
        var flow = layui.flow;
        // 流加载实例
        flow.load({
            elem: '#ID-flow-demo', // 流加载容器
            md: 10,	//与底部的临界距离，默认50。即当滚动条与底部产生该距离时，触发加载
            done: function (page, next) { // 执行下一页的回调
                var lis = [];
                // 模拟数据插入
                $.ajax({
                    type: "GET",
                    dataType: 'json',  // 返回数据的数据类型json
                    url: "{% url 'essay:essayajax' %}?page=" + page + "",
                    {#data: {pagesize: pages},  //传送的数据#}
                    success: function (res) {
                        //  console.log(res.data) debug
                        //   console.log(res.count) debug

                        layui.each(res.data, function (index, item) {
                            var html =
                                '<div class="layui-panel  panel-color">' +
                                '<div style="padding:0 8px ;">' +
                                '<fieldset class="layui-elem-field">' +
                                ' <legend style="font-size: 30px;color:#306B59">' + item.title + '</legend>' +
                                '<div class="layui-field-box ">' +
                                '<span style="font-size: 15px;"><strong><em> ' + item.typedata + ' -- ' + item.createtime + ' </em></strong></span>' +
                                ' <hr class="layui-border-red">' +
                                '<div style="width: 1660px;height: 80px;"class="selector">' +
                                '<p class="text-overflow">' + item.content + '</p>' +
                                '</div>' +
                                '<br> <p id="essayClickBody' + item.essayid + '" essayid="' + item.essayid + '" class="read" > >>> 点击阅读</p>' +
                                '</div> </fieldset> </div>   </div><br>';
                            lis.push(html);
                        });
                        //执行下一页渲染，第二参数为：满足“加载更多”的条件，即后面仍有分页
                        //page为当前页   res.count为总页数     只有当前页小于 总页数时才执行
                        // console.log( page  , res.count)  debug
                        next(lis.join(''), page < res.count);
                        //文章点击
                        $('p[id^="essay"]').click(function () {
                            essayid = $(this).attr("essayid") // 获取essay属性值
                            $.ajax({
                                type: "GET",
                                dataType: 'json',
                                url: "{% url 'essay:getessay' %}?essayid=" + essayid + "",
                                success: function (res) {
                                    resdata = res.data[0];
                                    $('#body').empty()
                                    var html =
                                        '<div><span><h1 style="text-align: center"><b>' + resdata.title + '</b></h1></span><br>' +
                                        ' <span><h3  style="text-align: center">' + resdata.createtime + '更新 |' + resdata.typedata + '</h3></span><br><div class="content">' +
                                        resdata.content + '</div></div>'
                                    $('#body').html(html)
                                }
                            });
                        });
                    }
                });
            }
        });
    });

    //输入框点缀事件
    layui.use(function () {
        var form = layui.form;
        // 输入框点缀事件 - 搜索示例
        form.on('input-affix(search)', function (data) {
            var elem = data.elem; // 输入框
            var value = elem.value; // 输入框的值
            //console.log(value)   debug
            if (!value) {
                layer.msg('请输入搜索内容');
                return elem.focus()
            }
            ;
            // 模拟搜索跳转
            location.href = "{% url 'essay:essaysearch' %}?keywords=" + value;
        });
    });

    //最近文章点击
    layui.use(function () {
        var $ = layui.jquery
        $('p[id^="essay"]').click(function () {
            essayid = $(this).attr("essayid") // 获取essay属性值
            $.ajax({
                type: "GET",
                dataType: 'json',
                url: "{% url 'essay:getessay' %}?essayid=" + essayid + "",
                success: function (res) {
                    resdata = res.data[0];
                    $('#body').empty()
                    var html =
                        '<div><span><h1 style="text-align: center"><b>' + resdata.title + '</b></h1></span><br>' +
                        ' <span><h3  style="text-align: center">' + resdata.createtime + '更新 |' + resdata.typedata + '</h3></span><br><div class="content">' +
                        resdata.content + '</div></div>'
                    $('#body').html(html)
                }
            });
        });
    });

    //时间树点击
    layui.use(function () {
        var $ = layui.jquery
        $('#timetree').click(function () {
            $.ajax({
                type: "GET",
                dataType: 'json',
                url: "{% url 'essay:timetree' %}",
                success: function (res) {
                    $('#body').empty()
                    var html = '';
                    for (var i = 0; i < res.data.length; i++) {
                        // 为每个条目生成HTML片段
                        html += '<div class="layui-timeline-item">';
                        html += ' <i class="layui-icon layui-timeline-axis"></i>';
                        html += ' <div class="layui-timeline-content layui-text">';
                        html += ' <h3 class="layui-timeline-title">' + res.data[i].createtime + '</h3>';
                        html += '<p>' + res.data[i].event + '</p>';
                        html += ' </div></div>';
                    }
                    $('#body').html('<div class="layui-timeline content" style="display: grid;place-items: center;height: auto; ">' + html + '</div>')
                }
            });
        });
    });
</script>
<style>
    html, body {
        overflow-x: hidden; /* 隐藏水平滚动条 */
    }

    body {
        font-family: sans-serif !important;

    }

    li a {
        color: rgba(91, 91, 91, 0.93) !important
    }

    .alink {
        color: #6f6e78 !important
    }

    .content {
        padding: 0 55px 55px 55px;
        background-color: #ece0bc !important;
    }

    .parent {
        display: flex;
        flex-direction: column; /* 默认就是column，这里可以省略，但为了明确表示垂直布局故保留 */
        height: 100%; /* 父元素需要一个确定的高度 */
    }

    .child-at-bottom {
        margin-top: auto; /* 这将把该子元素推到其他内容下方 */
    }

    .text-overflow {
        overflow: hidden;
        -webkit-line-clamp: 3;
        display: -webkit-box;
        -webkit-box-orient: vertical;
        text-overflow: ellipsis;
    }

    .selector {
        font-size: 20px !important; /* 设置字体大小为20像素 */
        font-family: Arial, sans-serif !important; /* 设置字体类型，优先使用Arial，如果用户设备上没有Arial，则使用任何无衬线字体 */
        color: rgba(107, 106, 106, 0.93) !important; /* 设置字体颜色为深灰色，#333 是十六进制颜色代码 */
    }

    .selector * {
        font-size: inherit; /* 继承字体大小 */
        font-family: inherit; /* 继承字体类型 */
        color: inherit; /* 继承字体颜色 */
    }

    .panel-color {
        background-color: #CDDCDC;
        background-image: radial-gradient(at 50% 100%, rgba(255, 255, 255, 0.50) 0%, rgba(0, 0, 0, 0.50) 100%), linear-gradient(to bottom, rgba(255, 255, 255, 0.25) 0%, rgba(0, 0, 0, 0.25) 100%);
        background-blend-mode: screen, overlay;
    }

    .read {
        color: #306B59 !important
    }

    .read:hover {
        color: #f35d5d !important;
        cursor: pointer;
    }

    /* 定义滚动条的整体宽高 */
    ::-webkit-scrollbar {
        width: 10px; /* 对于垂直滚动条的宽度 */
        height: 10px; /* 对于水平滚动条的高度 */
    }

    /* 定义滚动条的轨道 */
    ::-webkit-scrollbar-track {
        background-color: rgb(239, 218, 158); /* 轨道颜色 */
        border-radius: 5px; /* 轨道圆角 */
    }

    /* 定义滚动条滑块 */
    ::-webkit-scrollbar-thumb {
        background-color: #5da7f8; /* 滑块颜色 */
        border-radius: 10px; /* 滑块圆角 */
    }

    /* 当滑块悬停时改变颜色 */
    ::-webkit-scrollbar-thumb:hover {
        background-color: #de4646;
    }


</style>
</body>

</html>