essay/urls.py
from django.urls import path

from . import views

# essay模块的路由

app_name = 'essay'  # 一定要指定命名空间

urlpatterns = [
    path('', views.index, name='index'),
    path('essayajax', views.essayajax, name='essayajax'),
    path('essaysearch',views.essaySearch, name='essaysearch'),
    path('getessay',views.getEssay, name='getessay'),
    path('timetree',views.timeTree, name='timetree')
]

sunshinelife/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('user/', include("user.urls")),  # 导入user模块的路由

    path('', include("essay.urls"))   # 导入essay模块的路由

    # 登录路由查询字符的方式
    # path('user', user_view.login),
    # 登录路由在path中携带
    # 限制类型  int  str  slug uuid path
    # path('user/<int:user_id>/<user_name>', user_view.login_path)
]

user/urls.py
from django.urls import path

from . import views

# user模块的路由

app_name = 'user'  # 一定要指定命名空间

urlpatterns = [
    #用户
    path('index', views.index, name='user_index'),
    path('login', views.user_login, name='user_login'),
    path('register', views.register, name='user_register'),
    path('userupdate', views.userUpdate, name='user_update'),

    #类型
    path('gettype', views.getType, name='user_gettype'),
    path('addtype', views.addType, name='user_addtype'),
    path('alltype', views.allType, name='user_alltype'),
    path('updatetype', views.updateType, name='user_updatetype'),
    path('updatetypestu', views.updateTypeStu, name='user_updatetypestu'),


    #文章

    path('getessay', views.getEssay, name='user_getessay'),
    path('addessay', views.addEssay, name='user_addessay'),
    path('allessay', views.allEssay, name='user_allessay'),
    path('updateessay', views.updateEssay, name='user_updateessay'),
    path('updateessaystu', views.updateEssayStu, name='user_updateessaystu'),

    #公告
    path('getside', views.getSide, name='user_getside'),
    path('addside', views.addSide, name='user_addside'),
    path('allside', views.allSide, name='user_allside'),

    # 类型
    path('gettree', views.getTree, name='user_gettree'),
    path('addtree', views.addTree, name='user_addtree'),
    path('alltree', views.allTree, name='user_alltree'),
    path('updatetree', views.updateTree, name='user_updatetree'),
    path('updatetreestu', views.updateTreeStu, name='user_updatetreestu'),

    # path('url', views.url, name='user_login'),
    # path('add', views.user_add, name='user_add'),
    # path('query',views.user_query,name='user_query'),
    # path('update', views.user_update, name='user_update'),
    # path('delete', views.user_delete, name='user_del')
]

user/models.py
import datetime

from django.db import models
from django.forms import EmailField


# 默认生成主键 id
class UserMsg(models.Model):
    userid = models.CharField(max_length=30)  # 账号
    show = models.TextField(null=True, blank=True)  # 简介
    created = models.DateTimeField(auto_now_add=True)  # 创建时间
    updatetime = models.DateTimeField(auto_now=True)  # 修改时间
    remark = models.CharField(max_length=60, null=True, blank=True)  # 备注

    class Meta:
        db_table = 'user_msg'  # 设置表名

user/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import HttpResponse, render, redirect
from django.urls.base import reverse_lazy

import time
from django.views.decorators.http import require_http_methods

from .form import *
from .models import UserMsg
from essay.models import essay, essay_type, side, timeTree  # 导入essay app 模型
from essay.form import *

from django.contrib.auth import get_user_model, login

from tool.Tool import *

Sys_User = get_user_model()


# 在url中携带参数
# 通过查询字符的方式（query string） http://127.0.0.1:8000/user?id=3&name=ppp
# 在path中携带  http://127.0.0.1:8000/user/2/hhh


# 用户主页
@login_required(login_url=reverse_lazy('user:user_login'))
def index(request):
    session_id = request.session["id"]  # 获取session中的id
    sys_user = Sys_User.objects.get(id=session_id)
    datatime = time.strftime("%Y年%m月%d日 %H:%M:00", time.localtime())
    context = {
        'name': sys_user.username,
        'time': datatime
    }
    return render(request, 'userIndex.html', context=context)


# 用户注册
@require_http_methods(['GET', 'POST'])
def register(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        code = request.POST.get("code")
        if code != 'SSSSS':
            return HttpResponse("注册码有误")
        else:
            form = RegisterForm(request.POST)
            if form.is_valid():
                username = form.data.get("username")
                email = form.data.get("email")
                password = form.data.get("password")
                data_userid = Sys_User.objects.filter(email=email)
                if len(data_userid) != 0:
                    return HttpResponse("邮箱重复！")
                else:
                    Sys_User.objects.create_user(username=username, email=email, password=password)
                    # 检索出用户信息 储存在USERMSG表中
                    sys_user = Sys_User.objects.get(email=email, username=username)
                    UserMsg.objects.create(userid=sys_user.id)
                    context = {
                        'email': email,
                    }
                    return render(request, 'login.html', context=context)
            else:
                return HttpResponse("注册格式有误")


# 用户登陆验证逻辑
@require_http_methods(['GET', 'POST'])
def user_login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        loginform = LoginForm(request.POST)
        if loginform.is_valid():
            email = loginform.cleaned_data.get('email')
            password = loginform.cleaned_data.get('password')
            sys_user = Sys_User.objects.filter(email=email).first()
            if sys_user and sys_user.check_password(password):
                # 登录
                login(request, sys_user)
                request.session["id"] = sys_user.id  # 向session中存储用户唯一键
                # 过期时间直接设置为零
                request.session.set_expiry(0)
                return redirect('user:user_index')
            else:
                return HttpResponse("验证失败")
        else:
            return HttpResponse("数据有误")


# 修改个人信息
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET', 'POST'])
def userUpdate(request):
    if request.method == 'GET':  # 通过get方法获取用户的基本信息回填表填
        session_id = request.session["id"]
        user = UserMsg.objects.get(userid=session_id)
        sys_user = Sys_User.objects.get(id=session_id)
        context = {'username': sys_user.username, 'show': user.show}  # 信息拼接
        return render(request, 'userUpdate.html', context=context)
    else:
        session_id = request.session["id"]  # 获取session中的id
        # 保存
        show = request.POST.get('show')
        user = UserMsg.objects.get(userid=session_id)
        user.show = show
        user.save()
        username = request.POST.get('username')
        sys_user = Sys_User.objects.get(id=session_id)
        sys_user.username = username
        sys_user.save()
        context = {'username': sys_user.username, 'show': user.show}
        return render(request, 'userUpdate.html', context=context)


# 文章类型页面
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET', 'POST'])
def getType(request):
    return render(request, 'allType.html')


# 查看全部类型
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET', 'POST'])
def allType(request):
    if request.method == 'GET':
        all_type = essay_type.objects.all()
        json = []
        for item in all_type:
            item.status = '启用' if item.status == '1' else '禁用'
            json.append({
                'typeid': item.typeid,
                'type': item.type,
                'remark': item.remark,
                'status': item.status
            })
        context = result(1, 200, all_type.count(), json)
        return JsonResponse(context, safe=False)


# 添加类型
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['POST'])
def addType(request):
    if request.method == 'POST':
        type = request.POST.get('type')
        essay_type(type=type, status=1).save()  # 保存的类型并启用
        return redirect('user:user_gettype')  # 返回表格界面


# 编辑类型
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['POST'])
def updateType(request):
    if request.method == 'POST':
        typeid = request.POST.get('typeid')
        type = request.POST.get('type')
        remark = request.POST.get('remark')
        data = essay_type.objects.get(typeid=typeid)
        data.type = type
        data.remark = remark
        data.save()
        return redirect('user:user_gettype')  # 返回表格界面


# 类型状态变更
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET'])
def updateTypeStu(request):
    if request.method == 'GET':
        typeid = request.GET.get('typeid')
        data = essay_type.objects.get(typeid=typeid)  # 根据数据库的状态值去改变
        # print(data.status)
        if data.status == '1' or data.status == 1:
            data.status = 0
        else:
            data.status = 1
        data.save()
        return redirect('user:user_gettype')  # 返回表格界面


# 文章页面
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET', 'POST'])
def getEssay(request):
    return render(request, 'allEssay.html')


# 查看文章全部
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET', 'POST'])
def allEssay(request):
    if request.method == 'GET':
        all_type = essay.objects.all().order_by('-created')
        json = []
        for item in all_type:
            item.status = '启用' if item.status == '1' else '禁用'
            item.created = getdatetime(item.created)
            json.append({
                'essayid': item.essayid,
                'typeid': item.typedata.typeid,
                'type': item.typedata.type,
                'title': item.title,
                'content': item.content,
                'created': item.created,
                'remark': item.remark,
                'status': item.status
            })
        context = result(1, 200, all_type.count(), json)
        return JsonResponse(context, safe=False)


# 新增文章
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET', 'POST'])
def addEssay(request):
    if request.method == 'GET':
        all_type = essay_type.objects.filter(status=1)
        data = []
        for item in all_type:
            data.append({
                'typeid': item.typeid,
                'type': item.type,
            })
        context = {"data": data}
        return render(request, 'addEssay.html', context=context)
    else:
        typeid = request.POST.get('typeid')
        type = essay_type.objects.get(typeid=typeid)  # 类型对象
        title = request.POST.get('title')
        content = request.POST.get('content')
        content_dispose = remove_background_styles(content)
        remark = request.POST.get('remark')

        essay.objects.create(typedata=type, title=title, content=content_dispose, remark=remark, status=1).save()
        return redirect('user:user_getessay')


# 文章状态变更
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET'])
def updateEssayStu(request):
    if request.method == 'GET':
        essayid = request.GET.get('essayid')
        data = essay.objects.get(essayid=essayid)  # 根据数据库的状态值去改变
        # print(data.status)
        if data.status == '1' or data.status == 1:
            data.status = 0
        else:
            data.status = 1
        data.save()
        return redirect('user:user_getessay')  # 返回表格界面


# 编辑文章
@login_required(login_url=reverse_lazy('user:user_login'))
@require_http_methods(['GET', 'POST'])
def updateEssay(request):
    if request.method == 'GET':
        # 获取文章类型
        all_type = essay_type.objects.filter(status=1)
        typedb = []
        for item in all_type:
            typedb.append({
                'typeid': item.typeid,
                'type': item.type,
            })
        essayid = request.GET.get('essayid')
        data = essay.objects.get(essayid=essayid)

        context = {"typedb": typedb,
                   "essayid": essayid,
                   "title": data.title,
                   "typeid": data.typedata.typeid,
                   "content": data.content,
                   "remark": data.remark,
                   }
        return render(request, 'updateEssay.html', context=context)
    else:
        typeid = request.POST.get('typeid')
        type_data = essay_type.objects.get(typeid=typeid)
        essayid = request.POST.get('essayid')
        title = request.POST.get('title')
        content = request.POST.get('content')
        content_dispose = remove_background_styles(content)
        remark = request.POST.get('remark')
        data = essay.objects.get(essayid=essayid)
        data.title = title

user/templates/allEssay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>类型详细</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'layui/layui.js' %}"></script>
</head>
<body>
<table class="layui-hide" id="typetable"></table>
<script type="text/html" id="toolbartypet">
    <button class="layui-btn layui-btn-lg" lay-event="addType">新增类型</button>
</script>
<script type="text/html" id="tooltypet">
    <div class="layui-clear-space">
        <a class="layui-btn layui-btn-xs" lay-event="edit">文章编辑</a>
        <a class="layui-btn layui-btn-xs" lay-event="change">文章变更状态</a>
    </div>
</script>

<div id="update" style="display: none;">
    <form class="layui-form layui-form-pane" method="post" action="{% url 'user:user_updatetype' %}">
        {% csrf_token %}
        <input type="hidden" name="typeid" id="typeid" value=" " lay-verify="required">
        <div class="layui-form-item">
            <label class="layui-form-label">类型</label>
            <div class="layui-input-block">
                <input type="text" name="type" id="type" autocomplete="off" value="" placeholder="类型"
                       lay-verify="required"
                       class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <input type="text" name="remark" id="remark" autocomplete="off" value=" " placeholder="备注"
                       class="layui-input">
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center">
            <button class="layui-btn" lay-submit lay-filter="demo2">确认</button>
        </div>
    </form>
</div>
<div id="addtype" style="display: none;">
    <form class="layui-form layui-form-pane" action="{% url 'user:user_addtype' %}" method="post">
        {% csrf_token %}
        <div class="layui-form-item">
            <label class="layui-form-label">类型</label>
            <div class="layui-input-block">
                <input type="text" name="type" autocomplete="off" value="" placeholder="输入新增类型"
                       lay-verify="required"
                       class="layui-input">
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center">
            <button class="layui-btn" lay-submit lay-filter="demo2">新增</button>
        </div>
    </form>
</div>
<script>
    layui.use(['table', 'jquery', 'layer'], function () {
        let layer = layui.layer;
        let table = layui.table;
        let $ = layui.jquery;
        // 已知数据渲染
        table.render({
            elem: '#typetable',
            toolbar: '#toolbartypet',
            url: '{% url 'user:user_allessay' %}',
            method: "get",
            defaultToolbar: [],
            response: {
                statusCode: 200 //规定成功的状态码，默认：0
            },
            cols: [[ //标题栏
                {field: 'essayid', title: '文章ID', sort: true},
                {field: 'title', title: '文章标题'},
                {field: 'typeid', title: '类型ID'},
                {field: 'type', title: '文章类型'},
                {field: 'created', title: '发表时间', sort: true},
                {field: 'content', title: '文章代码'},
                {field: 'status', title: '状态'},
                {field: 'remark', title: '备注'},
                {fixed: 'right', title: '操作', toolbar: '#tooltypet'}
            ]],

        })
        ;
        // 工具栏事件
        table.on('toolbar(typetable)', function (obj) {
            switch (obj.event) {
                case 'addType':
                    layer.confirm('是否跳转新增文章界面?', function () {
                        location.href = "{% url 'user:user_addessay' %}"
                    })
            }
        });
        // 触发单元格工具事件
        table.on('tool(typetable)', function (obj) { // 双击 toolDouble
            var data = obj.data; // 获得当前行数据
            essayid = data.essayid
            if (obj.event === 'edit') {
                layer.confirm('是否跳转修改文章界面?', function () {
                    location.href = "{% url 'user:user_updateessay' %}?essayid="+essayid+"";
                })
            } else if (obj.event === 'change') {
                $.get('{% url 'user:user_updateessaystu' %}', {essayid: essayid}, function (data, status) {
                    location.reload();
                })
            }
        });
    });


</script>

</body>

</html>

user/templates/allTimeTree.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>类型详细</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'layui/layui.js' %}"></script>
</head>
<body>
<table class="layui-hide" id="typetable"></table>
<script type="text/html" id="toolbartypet">
    <button class="layui-btn layui-btn-lg" lay-event="addtree">新增事件</button>
</script>
<script type="text/html" id="tooltypet">
    <div class="layui-clear-space">
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs" lay-event="change">变更状态</a>
    </div>
</script>

<div id="update" style="display: none;">
    <form class="layui-form layui-form-pane" method="post" action="{% url 'user:user_updatetree' %}">
        {% csrf_token %}
        <input type="hidden" name="id" id="id" value=" ">
        <div class="layui-form-item">
            <label class="layui-form-label">事件</label>
            <div class="layui-input-block">
                <input type="text" name="event" id="event" autocomplete="off" value="" placeholder="事件"
                       lay-verify="required"
                       class="layui-input">
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center">
            <button class="layui-btn" lay-submit lay-filter="demo2">确认</button>
        </div>
    </form>
</div>
<div id="addtree" style="display: none;">
    <form class="layui-form layui-form-pane" action="{% url 'user:user_addtree' %}" method="post">
        {% csrf_token %}
        <div class="layui-form-item">
            <label class="layui-form-label">事件</label>
            <div class="layui-input-block">
                <input type="text" name="event" autocomplete="off" value="" placeholder="输入新增事件"
                       lay-verify="required"
                       class="layui-input">
            </div>
        </div>
        <div class="layui-form-item" style="text-align: center">
            <button class="layui-btn" lay-submit lay-filter="demo2">新增</button>
        </div>
    </form>
</div>
<script>
    layui.use(['table', 'jquery', 'layer'], function () {
        let layer = layui.layer;
        let table = layui.table;
        let $ = layui.jquery;
        // 已知数据渲染
        table.render({
            elem: '#typetable',
            toolbar: '#toolbartypet',
            url: '{% url 'user:user_alltree' %}',
            method: "get",
            defaultToolbar: [],
            response: {
                statusCode: 200 //规定成功的状态码，默认：0
            },
            cols: [[ //标题栏
                {field: 'id', title: 'ID', sort: true},
                {field: 'event', title: '事件'},
                {field: 'created', title: '时间', sort: true},
                {field: 'status', title: '状态'},
                {fixed: 'right', title: '操作', toolbar: '#tooltypet'}
            ]],
        })
        ;
        // 工具栏事件
        table.on('toolbar(typetable)', function (obj) {
            switch (obj.event) {
                case 'addtree':
                    layer.open({
                        type: 1,
                        area: ['360px', '500px'],
                        skin: 'layui-layer-rim', // 加上边框
                        content: $('#addtree'),
                    });
            }
        });


        // 触发单元格工具事件
        table.on('tool(typetable)', function (obj) { // 双击 toolDouble
            var data = obj.data; // 获得当前行数据
            id = data.id
            data_event = data.event
            if (obj.event === 'edit') {
                layer.open({
                    title: '编辑 ID:' + id ,
                    type: 1,
                    area: ['360px', '500px'],
                    content: $('#update'),
                    success: function (index, layero) {
                        $("#update").removeAttr("style", "");
                        $("#id").val(id);
                        $("#event").val(data_event);
                    }
                });
            } else if (obj.event === 'change') {
                $.get('{% url 'user:user_updatetreestu' %}', {id: id}, function (data, status) {
                    location.reload();
                })
            }
        });
    });


</script>

</body>

</html>

user/templates/allType.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>类型详细</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'layui/layui.js' %}"></script>
</head>
<body>
<table class="layui-hide" id="typetable"></table>
<script type="text/html" id="toolbartypet">
    <button class="layui-btn layui-btn-lg" lay-event="addType">新增类型</button>
</script>
<script type="text/html" id="tooltypet">
    <div class="layui-clear-space">
        <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
        <a class="layui-btn layui-btn-xs" lay-event="change">变更状态</a>
    </div>
</script>

<div id="update" style="display: none;">
    <form class="layui-form layui-form-pane" method="post" action="{% url 'user:user_updatetype' %}">
        {% csrf_token %}
        <input type="hidden" name="typeid" id="typeid" value=" " lay-verify="required">
        <div class="layui-form-item">
        <label class="layui-form-label">类型</label>
        <div class="layui-input-block">
            <input type="text" name="type" id="type" autocomplete="off" value="" placeholder="类型"
                   lay-verify="required"
                   class="layui-input">
        </div></div>
            <div class="layui-form-item">
        <label class="layui-form-label">备注</label>
        <div class="layui-input-block">
            <input type="text" name="remark" id="remark" autocomplete="off" value=" " placeholder="备注"
                   class="layui-input">
        </div></div>
        <div class="layui-form-item" style="text-align: center">
            <button class="layui-btn" lay-submit lay-filter="demo2">确认</button>
        </div>
    </form>
</div>
<div id="addtype" style="display: none;">
<form class="layui-form layui-form-pane" action="{% url 'user:user_addtype' %}" method="post" >
    {% csrf_token %}
    <div class="layui-form-item">
        <label class="layui-form-label">类型</label>
        <div class="layui-input-block">
            <input type="text" name="type" autocomplete="off" value="" placeholder="输入新增类型" lay-verify="required"
                   class="layui-input">
        </div>
    </div>
    <div class="layui-form-item" style="text-align: center">
        <button class="layui-btn" lay-submit lay-filter="demo2">新增</button>
    </div>
</form>
</div>
<script>
    layui.use(['table', 'jquery', 'layer'], function () {
        let layer = layui.layer;
        let table = layui.table;
        let $ = layui.jquery;
        // 已知数据渲染
        table.render({
            elem: '#typetable',
            toolbar: '#toolbartypet',
            url: '{% url 'user:user_alltype' %}',
            method: "get",
            defaultToolbar: [],
            response: {
                statusCode: 200 //规定成功的状态码，默认：0
            },
            cols: [[ //标题栏
                {field: 'typeid', title: 'ID', sort: true},
                {field: 'type', title: '文章类型'},
                {field: 'remark', title: '备注'},
                {field: 'status', title: '状态'},
                {fixed: 'right', title: '操作', toolbar: '#tooltypet'}
            ]],

        })
        ;
        // 工具栏事件
        table.on('toolbar(typetable)', function (obj) {
            switch (obj.event) {
                case 'addType':
                    layer.open({
                        type: 1,
                        area: ['360px', '500px'],
                        skin: 'layui-layer-rim', // 加上边框
                        content:  $('#addtype'),
                    });
            }
        });
        // 触发单元格工具事件
        table.on('tool(typetable)', function (obj) { // 双击 toolDouble
            var data = obj.data; // 获得当前行数据
            typeid = data.typeid
            type = data.type
            remark = data.remark
            if (obj.event === 'edit') {
                layer.open({
                    title: '编辑 ID:' + typeid,
                    type: 1,
                    area: ['360px', '500px'],
                    content: $('#update'),
                    success: function (index, layero) {
                        $("#update").removeAttr("style", "");
                        $("#typeid").val(typeid);
                        $("#type").val(type);
                        $("#remark").val(remark);
                    }
                });
            } else if (obj.event === 'change') {
                $.get('{% url 'user:user_updatetypestu' %}', {typeid: typeid}, function (data, status) {
                    location.reload();
                })
            }
        });
    });


</script>

</body>

</html>

user/templates/url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>url 页面</title>
</head>
<body>
<b>URL页面</b>
<p>name :{{ username }}</p>
<p>age :{{ age }}</p>
</body>
</html>

user/templates/userIndex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SunShine-Admin</title>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    <script src="{% static 'layui/layui.js' %}"></script>
    <link rel="icon" href="{% static 'img/sunshine.svg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'img/sunshine.svg' %}" type="image/x-icon">
</head>
<body>
<div class="layui-layout layui-layout-admin">
    {# csrf攻击凭证 #}
    {% csrf_token %}
    <div class="layui-header">
        <ul class="layui-nav layui-bg-black myheader" lay-bar="disabled"
            style="text-align: center;">
            <li class="layui-nav-item "><h1 class="layui-font-24">管理后台</h1></li>
            <li class="layui-nav-item" style="float: right">
                <h1 class="layui-font-18">您好！{{ name }}</h1>
            </li>
        </ul>
    </div>
    <div class="layui-side">
        <div class="layui-side-scroll" style="background-color: #bdc3c7  !important; ">
            <!-- 左侧导航区域 -->
            <ul class="layui-nav layui-nav-tree layui-bg-black mytree"
                lay-filter="test">
                <li class="layui-nav-item lay-accordion">
                    <a href="javascript:;" class="layui-font-20 ">博文管理</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url 'user:user_getessay' %}" class="layui-font-18"
                               target="iframeMain">博文详细</a></dd>
                        <dd><a href="{% url 'user:user_addessay' %}" class="layui-font-18"
                               target="iframeMain">新增博文</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item "><a href="{% url 'user:user_gettype' %}" target="iframeMain"
                                               class="layui-font-20">
                    文章类型管理 </a>
                </li>
                <li class="layui-nav-item "><a href="{% url 'user:user_getside' %}" target="iframeMain"
                                               class="layui-font-20">
                    公告管理 </a>
                </li>
                <li class="layui-nav-item "><a href="{% url 'user:user_gettree' %}" target="iframeMain"
                                               class="layui-font-20">
                    时间树管理 </a>
                </li>
                <li class="layui-nav-item"><a class="layui-font-20" href="{% url 'user:user_update' %}"
                                              target="iframeMain" id="userupdate">
                    个人资料编辑</a></li>
                <li class="layui-nav-item"><a href="{% url 'essay:index' %}" class="layui-font-20">
                    返回主页</a></li>
            </ul>
        </div>
    </div>
    <div class="layui-body" style="background-color: #ECEBDE">

        <div style="padding: 15px;">
            <div class="layui-card layui-panel">
                <div class="layui-card-header layui-font-18">
                    {{ time }}
                </div>
                <div class="layui-card-body" style="text-align: center">
                    <iframe class="layadmin-iframe" style=" width: 1660px; height: 77vh;" name="iframeMain"

                            frameborder="0" scrolling="yes"></iframe>
                </div>
            </div>
            <br><br>
        </div>
    </div>
</div>
<script>
    //JS
    layui.use(['element', 'layer', 'util', 'jquery'], function () {
        var element = layui.element;
        var layer = layui.layer;
        var util = layui.util;
        var $ = layui.jquery;

        util.event('lay-header-event', {
            menuLeft: function (othis) { // 左侧菜单事件
                layer.msg('展开左侧菜单的操作', {icon: 0});
            },
            menuRight: function () {  // 右侧菜单事件
                layer.open({
                    type: 1,
                    title: '更多',
                    content: '<div style="padding: 15px;">处理右侧面板的操作</div>',
                    area: ['260px', '100%'],
                    offset: 'rt', // 右上角
                    anim: 'slideLeft', // 从右侧抽屉滑出
                    shadeClose: true,
                    scrollbar: false
                });
            }
        });
    });
</script>
</body>

<style>
    .myheader {
        background: linear-gradient(90deg, #7D8E7D 31%, #2c3e50 100%) !important;
    }

    .mytree {
        background: linear-gradient(0deg, #2980B9 39%, #6DD5FA 95%, #FFFFFF 100%) !important;
    }

</style>
</html>